Adopt MultiBase wire contracts

diff --git a/scripts/xcode-test-harness b/scripts/xcode-test-harness
--- a/scripts/xcode-test-harness
+++ b/scripts/xcode-test-harness
@@ -125,11 +125,11 @@ case "$TEST_TRAITS" in
   "")
     default_expected_test_count=48
     ;;
-  "MultipleBases")
+  "MultiBase")
     default_expected_test_count=51
     ;;
   *)
-    echo "error: DATABASE_CLIENT_TEST_TRAITS must be empty or MultipleBases" >&2
+    echo "error: DATABASE_CLIENT_TEST_TRAITS must be empty or MultiBase" >&2
     exit 2
     ;;
 esac
@@ -178,7 +178,7 @@ if [[ -n "$TEST_TRAITS" ]]; then
     --exclude '*.xcresult' \
     "$ROOT_DIR/" "$source_root/"
   perl -0pi -e '
-    my $insertions = s/(\n    traits: \[\n)/$1        .default(enabledTraits: ["MultipleBases"]),\n/s;
+    my $insertions = s/(\n    traits: \[\n)/$1        .default(enabledTraits: ["MultiBase"]),\n/s;
     die "package trait list was not found\n" unless $insertions == 1;
   ' "$source_root/Package.swift"
   build_root="$source_root"
